//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.24 at 09:47:27 PM PDT 
//


package com.api.shipping.usps;


import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.api.shipping.usps package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.api.shipping.usps
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RateV3Request.Package }
     * 
     */
    public RateV3Request.Package createRateV3RequestPackage() {
        return new RateV3Request.Package();
    }

    /**
     * Create an instance of {@link RateV3Request }
     * 
     */
    public RateV3Request createRateV3Request() {
        return new RateV3Request();
    }

    /* Create an instance of {@link RateV3Response }
     *
     */
    public RateV3Response createRateV3Response() {
        return new RateV3Response();
    }

    /**
     * Create an instance of {@link RateV3Response.Package }
     *
     */
    public RateV3Response.Package createRateV3ResponsePackage() {
        return new RateV3Response.Package();
    }

    /**
     * Create an instance of {@link RateV3Response.Package.Postage }
     *
     */
    public RateV3Response.Package.Postage createRateV3ResponsePackagePostage() {
        return new RateV3Response.Package.Postage();
    }

}
